apiVersion: v1
kind: Pod
metadata:
  name: large-resource-pod
spec:
  containers:
  - name: large-container
    image: nginx:1.21
    resources:
      requests:
        memory: "2Gi"
        cpu: "1500m"
      limits:
        memory: "3Gi"
        cpu: "2500m"
