apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
  - default:
      memory: "128Mi"
      cpu: "200m"
    defaultRequest:
      memory: "64Mi"
      cpu: "100m"
    type: Container
