apiVersion: v1
kind: Pod
metadata:
  name: resource-demo-pod
  labels:
    app: resource-demo
spec:
  containers:
  - name: demo-container
    image: nginx:1.21
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
