apiVersion: v1
kind: Pod
metadata:
  name: problematic-pod
spec:
  containers:
  - name: problem-container
    image: nginx:1.21
    resources:
      requests:
        memory: "1Gi"
        cpu: "800m"
      limits:
        memory: "1.5Gi"
        cpu: "1200m"
